# Generated by Django 4.2.6 on 2023-10-15 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommercesite', '0004_remove_product_category_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='category_id',
        ),
    ]
